// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeachSys.Migrations
{
    [DbContext(typeof(BeachSysContext))]
    [Migration("20220616142213_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BeachSys.Models.Armario", b =>
                {
                    b.Property<int>("ArmarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("PontoX")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PontoY")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Regiao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ArmarioId");

                    b.ToTable("Armario");
                });

            modelBuilder.Entity("BeachSys.Models.Cadastro", b =>
                {
                    b.Property<int>("CadastroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("CadastroId");

                    b.ToTable("Cadastro");
                });

            modelBuilder.Entity("BeachSys.Models.Compartimento", b =>
                {
                    b.Property<int>("CompartimentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ArmarioId")
                        .HasColumnType("int");

                    b.Property<int?>("CadastroId")
                        .HasColumnType("int");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Regiao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Tamanho")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Trancado")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("CompartimentoId");

                    b.HasIndex("ArmarioId");

                    b.HasIndex("CadastroId");

                    b.ToTable("Compartimento");
                });

            modelBuilder.Entity("BeachSys.Models.Compartimento", b =>
                {
                    b.HasOne("BeachSys.Models.Armario", "Armario")
                        .WithMany("Compartimento")
                        .HasForeignKey("ArmarioId");

                    b.HasOne("BeachSys.Models.Cadastro", "Cadastro")
                        .WithMany()
                        .HasForeignKey("CadastroId");
                });
#pragma warning restore 612, 618
        }
    }
}
